name: picrust2-dev
channels:
- conda-forge
- r
- bioconda
- defaults

dependencies:
- h5py
- joblib
- numpy=1.13
- python=3.6.5
- r-base
- r-castor
- glpk
- biom-format
- pytest
- pytest-cov
- boost
- gcc_linux-64
- gxx_linux-64
- gfortran_linux-64
- bison
- flex
- boost
