name: picrust2-dev
channels:
- conda-forge
- r
- bioconda
- defaults

dependencies:
- h5py
- joblib
- numpy=1.13
- python=3.6.5
- r-base
- r-ape
- r-castor
- rpy2
- glpk
- pip:
  - biom-format
  - pytest
  - pytest-cov
